### ISSUE TITLE
Conflict Battery System causing blackscreen

### ISSUE THREAD

**Issue by DaniellMesquita** [Software-js/WS.js#248]

**Comment by sparkychild** [comment]
i have not done jquery yet, so you'll have to figure out how to incorporate that in there. the issue is that it cant read teh $ before the ()

from what i see in the code you may have to put a ``jQuery(document).ready(function($){`` around it so there is a $ to work with.

in javascript console i see a few errors (http://prntscr.com/ay1aqh)
```
launcher.js:1 Uncaught TypeError: $ is not a function
framework.js:53 Uncaught TypeError: $ is not a function
software-js.github.io/:25 Uncaught TypeError: $ is not a function
```
I'm guessing you probably have to pass $ into there using ``jQuery(document).ready(function($){``

**Comment by DaniellMesquita** [comment]
@sparkychild Thank you! The problem is with battery.js that have conflicts with jQuery. I've filled a bug issue now. https://github.com/miguelmota/battery/issues/4
Who can solve it is the owner of battery.js
He will read my issue and your reports+solutions. Thank you very much.

**Comment by DaniellMesquita** [comment]
Fixed. Thanks to @sparkychild for trying solve it and @miguelmota for doing https://github.com/miguelmota/battery.js/commit/bca7e2d878fd9b06224d9e02a15f7caa02f5e18d.
